// lib/codewords.ts
// The word pool for codeword auth.
// Curated 5-letter words — common, unambiguous, nothing awkward.
// Loosely themed around the physical world: nature, spaces, movement, light.

export const WORDS = [
  // Nature
  "OCEAN","RIVER","CLOUD","BLOOM","STONE","GROVE","CLIFF","SHORE","FIELD","FROST",
  "EMBER","FLAME","DELTA","CORAL","CEDAR","MAPLE","BIRCH","HEATH","RIDGE","MARSH",
  "DUNES","CREEK","BROOK","BLUFF","CREST","FLORA","FLINT","GRAIN","HAVEN","INLET",
  // Objects + spaces
  "PLAZA","FRAME","CABIN","TOWER","LODGE","BENCH","PERCH","VAULT","ATTIC","FORGE",
  "QUILL","PRISM","BRACE","CLASP","FLARE","GABLE","LATCH","SCOUT","RELAY","PILOT",
  // Movement
  "DRIFT","GLIDE","SWEEP","CLIMB","QUEST","ROUTE","TRAIL","TRACK","SURGE","BOUND",
  "REACH","GUIDE","HOIST","SOLAR","CREST","DELTA","CROSS","MARCH","SHIFT","RALLY",
  // Colours + light
  "AMBER","IVORY","SLATE","AZURE","TAWNY","OLIVE","OCHRE","PEARL","EBONY","BLUSH",
  "LILAC","MAUVE","SANDY","SMOKY","MISTY","DUSKY","LUSTY","RUSTY","DUSTY","PASTY",
  // Clean + simple
  "APPLE","BREAD","BRUSH","BURST","CHESS","CRISP","DENIM","DRAMA","EAGLE","EARTH",
  "EASEL","EVOKE","EXCEL","EXIST","FABLE","FAITH","FANCY","FEAST","FIFTH","FIGHT",
  "FINAL","FIRST","FJORD","FLOAT","FLOOR","FLUID","FLUTE","FOCAL","FOLIO","FORTE",
  "FORUM","FOYER","FRESH","FRONT","FUNGI","FUNKY","GUEST","GUILE","GUILD","GUSTO",
  "HAIKU","HAZEL","HEIST","HERBS","HINGE","HONEY","HONOR","HORSE","HOTEL","HUMAN",
  "HUMID","HUMOR","HUNCH","HYPER","IDEAL","INDEX","INDIE","INGOT","INLAY","INPUT",
  "JOUST","JUDGE","JUICE","JUMBO","KAYAK","KNACK","KNEEL","KNIFE","KNOCK","KNOWN",
  "LABEL","LANCE","LAPSE","LASER","LATER","LATHE","LAUGH","LAYER","LEARN","LEASE",
  "LIGHT","LIMIT","LINEN","LINER","LOCAL","LOGIC","LOYAL","LUCID","LUCKY","LUNAR",
  "LYRIC","MAGIC","MAJOR","MANOR","MATCH","MIRTH","MITRE","MIXED","MODAL","MODEL",
  "MOOSE","MORAL","MOSSY","MOTIF","MOTOR","MOTTO","MOUNT","MOUSE","MURAL","MUSIC",
  "NAIVE","NAMED","NIFTY","NIGHT","NINJA","NOBLE","NOTCH","NOTED","NOVEL","NYLON",
  "OAKEN","OCCUR","OFFER","OFTEN","ONSET","OPTIC","ORBIT","ORDER","OUTER","OZONE",
  "PAINT","PAPER","PARTS","PASTA","PATCH","PINCH","PITCH","PIVOT","PLACE","PLANK",
  "PLANT","PLEAT","PLUMB","PLUME","POINT","POISE","POLAR","POSED","POUCH","POUND",
  "POWER","PRESS","PRICE","PRIDE","PRIME","PRINT","PROBE","PRONE","PROOF","PROSE",
  "PROUD","PROXY","PULSE","PUNCH","PURSE","QUAKE","QUOTA","QUOTE","RAISE","RANCH",
  "RANGE","RAPID","RATIO","REALM","RENEW","RESIN","RIDER","RINSE","RIVET","ROBIN",
  "ROCKY","ROYAL","RUGBY","RULER","SAINT","SALSA","SAUCE","SAUNA","SAVOR","SCALE",
  "SCENE","SEIZE","SENSE","SERVE","SETUP","SEVEN","SHADE","SHAFT","SHAKE","SHARK",
  "SHARP","SHELF","SHELL","SHINE","SHIRT","SIGHT","SILKY","SINCE","SIXTH","SIXTY",
  "SKILL","SKIRT","SKULL","SLANT","SLICE","SLIDE","SLOPE","SLOTH","SMART","SMILE",
  "SMOKE","SNACK","SNAIL","SNARE","SOLID","SOLVE","SONIC","SOUTH","SPACE","SPARK",
  "SPEAR","SPECK","SPEED","SPEND","SPICE","SPOKE","SPOON","SPRAY","SPRIG","SQUAD",
  "SQUAT","STACK","STAFF","STAGE","STAIN","STAIR","STAKE","STALL","STAMP","STAND",
  "STARK","START","STASH","STATE","STAVE","STEAL","STEAM","STEEL","STEEP","STEER",
  "STERN","STICK","STIFF","STILL","STOCK","STOMP","STORE","STORM","STORY","STOUT",
  "STRAP","STRAW","STRAY","STRIP","STRUT","STUDY","STUMP","STYLE","SUGAR","SUITE",
  "SUPER","SWAMP","SWEAR","SWEEP","SWEET","SWIFT","SWIRL","SWOOP","SWORD","SYNTH",
  "TANGO","TAUNT","TERSE","THICK","THIRD","THORN","THUMP","TIDAL","TIGER","TIMER",
  "TITLE","TOAST","TODAY","TOKEN","TORCH","TOTAL","TOUCH","TOUGH","TOWEL","TRACE",
  "TRADE","TRAIN","TRAIT","TRAMP","TRIAD","TRIBE","TRIED","TROUT","TRULY","TRUSS",
  "TRUST","TRUTH","TULIP","TUNER","TUNIC","TWICE","TWILL","TWIRL","TWIST","ULTRA",
  "UNCLE","UNDER","UNIFY","UNION","UNITY","UNTIL","UPPER","USHER","USUAL","UTTER",
  "VALID","VALUE","VALVE","VAPOR","VISOR","VISTA","VITAL","VIVID","VOCAL","VOGUE",
  "VOICE","VOTER","VOUCH","WALTZ","WATCH","WATER","WEAVE","WEDGE","WHEAT","WHEEL",
  "WHIRL","WHITE","WIDER","WINDY","WIRED","WITTY","WOODY","WORLD","WORTH","WOVEN",
  "WRITE","YACHT","YOUNG","YOUTH","ZESTY",
];

// Deduplicated, 5-letter only
export const WORD_POOL = [...new Set(WORDS.filter(w => w.length === 5))];

export function randomCodeword(): string {
  return WORD_POOL[Math.floor(Math.random() * WORD_POOL.length)];
}
